vintagepc/MK404

parts/components/TMC2130.cpp
parts/components/TMC2130.h

Define the 0x6C CHOPCONF register and handle the DEDGE bit
See https://github.com/prusa3d/Prusa-Firmware/pull/2789
Pretty much plug&play ;)
Works on my machine™
Although we add the entire definition of CHOPCONF, all we care about is the DEDGE bit.

Implement DEDGE support in TMC2130

---

MK404.cpp

Moves glut back to the main thread.
Changed quit handling, may have improved #103, may have broken something else.
Yes. both GL windows now render correctly with Mesa and nvidia GL.
- fixes #188

188 freeglut threading

---

MK404.cpp
parts/boards/EinsyRambo.cpp

Removes a timer hack necessary due to wrong timer modes. Eliminates the need for `--no-hacks` with Marlin firmware.
None - should have unbroken things reliant on phase correct vs normal pwm subtleties.
yes, ran Marlin and Prusa firmware with no args/changes necessary anymore.
Cleans up some output spam if not running with `-vv`
- closes #75

Remove TIMSK hack, sync with simavr, timer fix

---

CMakeLists.txt
utility/GLObj.cpp
utility/MK3SGL.cpp
utility/MK3SGL.h
utility/MK3S_Bear.h
utility/MK3S_Full.h
utility/MK3S_Lite.h
utility/OBJCollection.h

Fixes a bug and some busted visuals as a result of the bear cleanup
Bug in GLObj would cause items to have inflated object indices, meaning any calls to set an object's properties by index would be changing the wrong object.
LCD brightness is still broken (will fix before merging)
Yes - MMU LEDs appear correct now, heatbed LED is in the correct place for both sets of visuals, sheet hides properly with `T` key, E-vis now spins a bit faster.
- Closes #218

218 broken visuals

---

parts/boards/EinsyRambo.cpp
parts/boards/MM_Control_01.cpp
parts/boards/Test_Board.cpp
parts/components/MMU2.cpp
parts/components/PINDA.cpp
parts/components/TMC2130.cpp
parts/components/TMC2130.h
utility/GLPrint.cpp

Changes the chopconf MRES handling to be easier to understand
MRES no longer alters the bounds of the motor. Instead, we always work in the "maximum" microstep resolution of the driver, and increment the internal step count by 2^mres.
Motor steps per MM for TMC drivers is now input as the steps/mm if the driver was operating at full resolution, not the Marlin/M92 value.
MMU now behaves as expected, main printer still moves as it should and the TMC automated test still works as expected.
Also fixed a nasty OOB bug in GLPrint.
- fixes #223

Improve MRES implementation

---

utility/GLPrint.cpp
utility/GLPrint.h

Avoid reallocating vectors with every push_back +avoid using std::vector when not necessary (replace with std::array if possible).
Constants VectorPrealoc and VectorPrealoc3 serve as initial preallocated size of the vectors, may be fine tuned for balanced usage of RAM.
There is much more space for optimization, but this one really brought the biggest benefit.
Removes lagging of recalculation of extrusion visualization (3d extrusion, Quad_HR)
Yes, I did 2 prints with extrusion visualization and compared to previous state. Each print took roughly 1 hour. The lagging disappeared, the rendering is visibly faster.
#114

Avoid reallocating vectors with every push_back

---

.github/workflows/cppcheck.yml
3rdParty/README.md
3rdParty/clang-tidy-to-github.py
CMakeLists.txt
MK404.cpp
parts/ScriptHost.cpp
parts/components/SDCard.cpp
parts/components/TMC2130.cpp
parts/components/TMC2130.h
utility/GLObj.h

Use Github annotations for code lint (#261)

---

MK404.cpp
utility/GLPrint.cpp
utility/GLPrint.h
utility/MK3SGL.cpp
utility/MK3SGL.h

Enables simulation of nonlinear TMC+motor on X,Y,E. When enabled, extrusion visualization tries to simulate nonlinear behavior of TMC+motor on the corresponding axis (or a set of axes). 
In this PR the nonlinearity is enabled by default - it is up to @vintagepc to decide whether this behavior should be enabled or disabled by default. If not, please comment out:
```
#define NONLINEAR_X
#define NONLINEAR_Y
#define NONLINEAR_E
```
Yes, simulating nonlinear behavior of TMC+motor on each of the axes has revealed serious print artefacts including the infamous "issue 602".
Possible future improvements:
- add a command line switch to enable/disable nonlinearity on an axis
- add a key shortcut to enable/disable nonlinearity - this may simplify investigation of artefacts a bit
Issue #114

Enable simulation of nonlinear TMC+motor on X,Y,E

---

parts/boards/Test_Board.cpp
parts/components/A4982.cpp

Fixes steps/mm being calculated incorrectly on miniRambo based boards.
None
Tested Prusa_MK2_mR13 variant with two different microstepping configurations. Both worked as expected. 
closes #253

Patch A4982 step-position conversion functions

---

utility/MK3SGL.cpp

Fixes a crash if the first E tick of a 3d print happens after the cycle count is > UINT32_MAX

Fix bug with deltaT and the first tick of a print

---

.github/workflows/tests.yml
parts/ADCPeripheral.h
parts/components/IRSensor.cpp
parts/components/IRSensor.h

Fixes a bug where the IRSensor digital IRQ does not update if the ADC isn't running
Yes - IR sensor now toggles as expected with firmware that does not start the ADC running.

Fix IRSensor if ADC isn't running

---

MK404.cpp
parts/Board.cpp
parts/components/HD44780.cpp
parts/components/HD44780.h
parts/components/HD44780GL.cpp
parts/components/uart_pty.cpp
utility/Config.h

Fixes some timing issues with Klipper and --skew-correction
Should have no net effect, but improves stability with skew correction.
Yes, locally was able to finally complete 3 benchys. 
Anything else you'd like us to know, or that may be beneficial if we need to maintain your contribution down the road?
- Closes #263

263 klipper take 2

---

parts/components/HD44780.cpp

Minor issue with LCD waitForText adding a lot of overhead due to display refreshes
Changed so that the "Line changed" flag is not updated if the character is udpated to the same thing. 
N/A
Might speed up the build automated tests. 
- Please list issue numbers related to your change, and use closing keywords if appropriate.

Stop WaitForText() check if there is no net change

---

parts/boards/EinsyRambo.cpp
parts/boards/EinsyRambo.h
parts/printers/Prusa_MK3S.cpp

Add UART1 aka RPi port for Einsy and MK3/s
Adds /tmp/simavr-uart1
- Start MK404 Prusa_MK3* with `-s` option 
- Try to connect with Octoprint to /tmp/simavr-uart0
- Result connection established
- Try to connect with Octoprint to /tmp/simavr-uart1
- Result connection fails
- Change in MK3/s under Settings -> RPI port to [On]
- Try to connect with Octoprint to /tmp/simavr-uart0
- Result connection fails
- Try to connect with Octoprint to /tmp/simavr-uart1
- Result connection established

Add UART1 aka RPi port to Einsy and MK3/s

---

parts/Board.cpp
parts/Board.h
parts/boards/EinsyRambo.cpp
parts/boards/EinsyRambo.h
parts/components/w25x20cl.cpp
parts/components/w25x20cl.h

If the languages are more than 64K the hex file splits them into sections. 
Handle this appropriately and load the additional pages. 
None - should fix larger language loads.
Can confirm that locally prior to this fix the community languages list was empty. After the fix, "Nederlands" appears as expected. 
- N/A, request by @3d-gussner

Fix multipage xflash load

---

CMakeLists.txt

Add a cmake include for simavr so that the project cleans and rebuilds together with the parent project. 
(also causes simavr to build the same type, e.g. release vs debug)

Use CMake for simavr

---

parts/components/PINDA.cpp
scripts/tests/test_PINDA.txt

Clamp probing coordinates to be always inside the mesh.
This is not correct when probing far away from the bed (PINDA shouldn't trigger at all), but for now this will do.
None.
Tests included.
Fixes #313

Fix PINDA crash when probing nearby bed margins

---

parts/Board.cpp
parts/Board.h

When enabling skew-correct, the "Lost X us!" messages can overwhelm the
output. Hide the message behind the verbosity switch.
A single -v switch now shows only uncompensated time, which is what
matters most.
-vv also shows the existing message as well.
No breaking behavior AFAIK.
Yes
n/a
none

Hide skew-correct's "Lost X us!" messages by default

---

parts/Board.cpp
parts/Board.h
scripts/tests/test_script_WFR.c
scripts/tests/test_script_WFR.txt

Adds ability to wait for board reset in a script. 
None - adds new capability
Not yet. 
- Closes #315

#315 - WaitForReset()

---

parts/KeyController.cpp
parts/components/SDCard.cpp
scripts/tests/test_lite_gfx_keys.txt

Minor features and fixes - a `?` hotkey and a null pointer dereference.
- Prints key reference to console if user presses `?` key
-  Sim no longer crashes if holding C and trhe card unmounts while mid-read.
- Fixes #323 
- Fixes #324

Misc fixes

---

parts/components/TMC2130.cpp
parts/components/TMC2130.h

The IOIN register contains some read-only state, along with the
driver version which can be used for IC checking.
Implement two fields (a fixed one and the version) for this purpose.
No behavioral change.
Money back guaranteed™
It would be nice to reject changes to some of these R/O registers in the future.
N/A

Implement the TMC2130 IOIN register version

---

parts/I2CPeripheral.h
parts/components/MCP23S17.h
parts/components/SDCard.h
parts/components/TMC2130.h
parts/components/usb_types.h
parts/components/usbip_types.h

Code consistency. In some places `__attribute__((__packed__))` was used in others `__attribute__((packed))`. I can't find any documentation that supports the later version but it could possibly be old syntax that still works in gcc.
No behavioural changes are expected.

Use consistent __attribute__((__packed__))

---

parts/components/PINDA.cpp

Minor performance tweak. When doing distance comparisons (c^2 = a^2+b^2), you can calculate c < 10, or you can do c^2 < 100.
Expect the same behaviour, and probably no noticeable performance gain, but still...
Yes, seems to work with MK3 as before.

Remove the need to calculate sqrt by using squared distance

---

MK404.cpp
parts/printers/Prusa_MK2_13.cpp
utility/Config.h
utility/EnabledType.h

When testing 3.10.x firmware on MK2 simulated hardware, I'd like the option to enable software PWM.
Adds the ability to use SoftPWM with the MK2 simulation. e.g 
`./MK404 Prusa_MK2_mR13 --softPWM enabled -f ...`
If not specified, and for other printer types, this will default to how its set to currently.
Works with the patched MK2 firmware, that relies on SoftPWM.
Only implemented for MK2, but if for example, someone wants to disable SoftPWM for MK3 this could be added.
#345

Implement commandline option to enable/disable softPWM #345

---

CMakeLists.txt
MK404.cpp
parts/ScriptHost.cpp
parts/ScriptHost.h
scripts/tests/extra_Scripting_stdio.py

Extend scripting to stdio so other programs can interface "live" with MK404. 
None, only adds functionality. 
Works locally. 
Scripting via stdio is only supported if no script file is loaded and --terminal is not enabled.
- Closes #350

Let ScriptHost read from stdio

---

parts/boards/EinsyRambo.cpp
parts/components/Heater.cpp
parts/components/Heater.h

Fix bug with MK3 heater getting stuck during UVLO or other reset
None - should fix broken behaviour, only adds code.
Resolves the issue on my end.

Fix heater freeze on power loss/reset

---

parts/Board.cpp
parts/boards/EinsyRambo.cpp
parts/boards/MiniRambo.cpp
parts/components/uart_pty.cpp
parts/components/uart_pty.h

Disables UART poll sleeping 
Speeds up the bootloader and other poll loops, at the expense of CPU usage and a tighter spinloop
- Closes #356

Always disable UART poll sleep
